env: dev
gcp:
  bucket:
    raw: ENV_GCP_GCS_RAW_BUCKET
    processed: ENV_GCP_GCS_PROCESSED_BUCKET
    archive: ENV_GCP_GCS_ARCHIVE_BUCKET
  blob_name:
    gmaps:
      reviews: "gmaps/detailed-reviews/*.parquet"
      places: "gmaps/attractions/*.parquet"
  bigquery:
    ods_dataset: ENV_BIGQUERY_ODS_DATASET
    dim_dataset: ENV_BIGQUERY_DIM_DATASET
    fact_dataset: ENV_BIGQUERY_FACT_DATASET
    mart_dataset: ENV_BIGQUERY_FACT_DATASET
  table_name:
    gmaps_places: "gmaps_places"
    gmaps_reviews: "gmaps_reviews"
